name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend'
      - '.github/workflows/maven.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend'
      - '.github/workflows/maven.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Run tests
        working-directory: frontend
        run: pnpm test

      - name: Run linter
        working-directory: frontend
        run: pnpm run lint
